[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "lltdrek"
version = "1.2.0"
description = "Package description"
authors = ["Luis Kuodrek <kuodrek@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/kuodrek/lltdrek"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = [{include = "lltdrek", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
matplotlib = "*"
numpy = ">=1.26.4"
polars = ">=1.0.0"
scipy = ">=1.12.0"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
pre-commit = "*"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E731"]

[tool.ruff.lint.isort]
known-first-party = ["lltdrek", "new"]
