name: Test library dependency with different Python versions

on:
  pull_request:
    branches:
      '*'

permissions:
  contents: read

jobs:
  versions:
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12, latest]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '${{ matrix.python-version }}'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
